import os
import glob
import tempfile
from typing import Optional
import yt_dlp
from groq import Groq

def transcribe_audio_groq(audio_path: str, api_key: str, language: Optional[str] = None) -> str:
    """
    Transcribes audio using Groq Whisper API (whisper-large-v3-turbo / whisper-large-v3).
    Extremely fast (~1-2s for a 60s short).
    """
    client = Groq(api_key=api_key)
    with open(audio_path, "rb") as file_data:
        kwargs = {
            "file": (os.path.basename(audio_path), file_data.read()),
            "model": "whisper-large-v3-turbo",
            "response_format": "text",
        }
        if language:
            kwargs["language"] = language
        
        transcription = client.audio.transcriptions.create(**kwargs)
        return str(transcription).strip()

def download_and_transcribe(url: str, groq_api_key: Optional[str] = None) -> str:
    """
    Downloads audio stream via yt-dlp into a temporary directory and transcribes it with Whisper.
    """
    if not groq_api_key:
        raise ValueError("GROQ_API_KEY is required for audio transcription fallback.")

    with tempfile.TemporaryDirectory() as tmpdir:
        output_template = os.path.join(tmpdir, "audio.%(ext)s")
        
        ydl_opts = {
            'format': 'bestaudio/best',
            'outtmpl': output_template,
            'quiet': True,
            'no_warnings': True,
            'noplaylist': True,
            'extractor_args': {
                'youtube': {
                    'player_client': ['android', 'ios']
                }
            },
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'm4a',
                'preferredquality': '128',
            }],
        }

        cookie_file = os.getenv("YOUTUBE_COOKIES_FILE", "cookies.txt")
        if os.path.exists(cookie_file):
            ydl_opts['cookiefile'] = cookie_file

        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([url])
        except Exception as e:
            raise RuntimeError(f"Failed to download audio via yt-dlp: {e}")

        # Find the downloaded file
        files = glob.glob(os.path.join(tmpdir, "audio.*"))
        if not files:
            raise FileNotFoundError("Audio file was not generated by yt-dlp.")

        audio_file = files[0]
        return transcribe_audio_groq(audio_file, api_key=groq_api_key)
